// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace MyGamePlayTags
{
	/** Input tags **/
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);

	/** Player tags **/
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);

	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);

	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);
	/** Enemy tags **/
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);

	/** Shared tags **/
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);

	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);

	TECHNICALTEST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

}